### ISSUE TITLE
SPI support?

### ISSUE THREAD

**Issue by masha256** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#17]
SPI support would be great for a) higher data rates, and b) support more than a few devices without having to use the i2c AD0 pull up/down trick (which for me wasn't working with the MPU-9250).

**Comment by santaimpersonator** [comment]
Unfortunately, this library was primarily written with our [SparkFun 9DoF Razor IMU](https://www.sparkfun.com/products/14001). If you want this library to work with SPI, you will probably need to modify and create the functionality in the [**util** folder](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/tree/master/src/util). As this IMU has been listed as EOL for a while, I am not sure we will be adding that feature to this library.

However, feel free to reach out in our [forums](https://forum.sparkfun.com/) to see if someone in the SparkFun community has worked on developing this functionality.
