### ISSUE TITLE
qToFloat mask uninitialized

### ISSUE THREAD

**Issue by vcortex91** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#2]
see lines 613-621 of src/SparkFunMPU9250-DMP.cpp

in MPU9250_DMP::qToFloat(), mask is not initialized to 0, and thus the top 32-q bits may be set to 1 undesirably

**Comment by jimblom** [comment]
Thanks for catching that! Issue should be address in commit 5aacad7.
