### ISSUE TITLE
MPU9250 I2C Address

### ISSUE THREAD

**Issue by hendrikjvr** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#20]
Hi, where is the MPU-9250 I2C Address of 0x68 defined, I can't find it? I need to set it to 0x69; the ADO pin, in my case, is set to 1 (HIGH).

**Comment by hendrikjvr** [comment]
I found it, line 436 and 516 in src/util/inv_mpu.c. Just changed 0x68 to 0x69. It works.

**Comment by matthewbaggett** [comment]
It would be really nice if there was a way to set this.
