### ISSUE TITLE
Using DMP and Wake on Motion 

### ISSUE THREAD

**Issue by method-nick** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#24]
Hi everyone,

I'd like to be able to use the DMP function of the MPU9250 with Wake On Motion (WOM).
I want the MPU to maintain it pose calculation (using DMP) when the microcontroller is in sleep mode.
I then want the MPU to wake the microcontroller on an acceleration trigger.

Is there any way to do this with this library? I have seen WOM implemented with the bolder-flight library:
https://github.com/bolderflight/MPU9250    

Any help is appreciated,
Nick

**Comment by santaimpersonator** [comment]
Unfortunately, that function wasn't created in the library (see examples and keywords). However, the [datasheet](https://cdn.sparkfun.com/assets/learn_tutorials/5/5/0/MPU9250REV1.0.pdf) has a specific example for configuring that functionality on pages 30-31.
