### ISSUE TITLE
Esp32 Serial1 not working with this Library

### ISSUE THREAD

**Issue by yo90bosses** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#25]
I'm using the ESP32 and if I use a different Library for the MPU9250 such as the one from BolderFlight then it works flawlessly. But when I use the sparkfun DMP Library with the DMP then it too works fine except for the serial1 where I have a SBUS receiver hooked up. It looks as if when the first bytes are recieved it works but after the first complete set of data I don't get anymore readings from the serial1. Everything else keeps working except for Serial1. And as I said other libraries do work with Serial1.
Also the Mpu9250 is connected over I2C.

**Comment by santaimpersonator** [comment]
Unfortunately, as stated in the [README.md](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/blob/master/README.md), this library was written specifically to work on SAMD processors used on our [SparkFun 9DoF Razor IMU](https://www.sparkfun.com/products/14001). If you want this library to work with an ESP32, you will probably need to modify the library for this issue.
