### ISSUE TITLE
 ~60 MS DELAY EVERY ~.5S

### ISSUE THREAD

**Issue by skemp117** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#36]
The IMU will have these random delays/gaps every so often where it doesn't transmit for around 60ms every .5 seconds or so: This is a zoomed in picture of an Euler angle output vs the time log:

![image](https://user-images.githubusercontent.com/44552792/69355844-80709400-0c50-11ea-9c9b-620141c944df.png)

All I am doing is checking fifoAvailable, then doing dmpUpdateFifo. There are no delays or loops in my code. The dmpbegin is initialized with a fifo rate of 200 Hz,

**Comment by santaimpersonator** [comment]
I would guess that this is probably one of two things, either you are logging data and the buffer being written to an SD card during that period or it is the time it takes to dump the FIFO buffer. However, without narrowing down where in the code this is occurring it is hard to investigate.

**Comment by santaimpersonator** [comment]
Closing due to lack of response.
