### ISSUE TITLE
Max sampling rate for DMP

### ISSUE THREAD

**Issue by yo90bosses** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#37]
If I'm using the DMP am I still able to pull gyro and accel data at 1khz?

**Comment by santaimpersonator** [comment]
As listed in the [hookup guide](https://learn.sparkfun.com/tutorials/9dof-razor-imu-m0-hookup-guide#getting-started-with-the-example-firmware), the example firmware (i.e. DMP) doesn't output data at that rate.

While we are not sure that it would work, you can modify the code for your purposes to test it out.
