### ISSUE TITLE
Use 2 IMU with 1 arduino

### ISSUE THREAD

**Issue by Bug38** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#42]
Hi !

I'm working on a project that needs 2 IMUs in order to locate 2 hardware pieces relatively to each other.

Is it possible to use 2 IMUs on a single MKRZERO ?

Thanks

Bug38

**Comment by santaimpersonator** [comment]
Hi there, it sounds like you are looking for [technical assistance](https://www.sparkfun.com/technical_assistance). Please use the link, to get started with posting a topic in our [forums](https://forum.sparkfun.com/). Our technical support team will do their best to assist you.

That being said, not if they have the same I2C address.
