### ISSUE TITLE
Heading isn't working

### ISSUE THREAD

**Issue by csmith105** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#6]
Using https://www.sparkfun.com/products/13762

The compass heading is useless.

**Comment by MichaelPriven** [comment]
It useless due to 2 reasons
1. the magnetometer isn't calibrated
2. there is an error in the function

> float MPU9250_DMP::computeCompassHeading(void)
{
	if (my == 0)
		**heading = (mx < 0) ? 180.0 : 0;**
	else
		heading = atan2(mx, my);
	
	if (heading > PI) heading -= (2 * PI);
	else if (heading < -PI) heading += (2 * PI);
	else if (heading < 0) heading += 2 * PI;
	
	heading*= 180.0 / PI;
	
	return heading;

> }
should be - 
heading = (mx<0) ? **PI** : 0;

**Comment by csmith105** [comment]
Is this pushed?

**Comment by MichaelPriven** [comment]
I'm not familiar with github, what do you mean by "pushed"?

**Comment by iamchrisb** [comment]
In general it just means "to upload the new code" (pushing)

**Comment by MichaelPriven** [comment]
OK, I dont know how to push :)

**Comment by iamchrisb** [comment]
Correct me if I am wrong, as far as I know, you are not the owner of this repository, this means you either have to make a pull request in git (you will find a lot on google for this topic) and the owner has to make the changes available for everyone or.. do a fork of this project and make the changes available on your own git-repository. I think, thats basically it. 💃
