### ISSUE TITLE
Help with supporting other platforms

### ISSUE THREAD

**Issue by sfranzyshen** [sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library#7]
Any chance this code could be ported to work with the esp8266 platform ...

**Comment by raomin** [comment]
I got it working with no issue on ESP8266 (Wemos D1).

**Comment by vyi** [comment]
@raomin Would you share how you got it to work with ESP8266 ?

**Comment by raomin** [comment]
I simply cloned the master, installed as Arduino library, opened MPU9250_DMP_Quaternion.ino in the exemple, selected the right board WeMos D1 R1 and changed `#define SerialPort SerialUSB` by `#define SerialPort Serial` to avoid `'SerialUSB' was not declared in this scope`

Then it compiles and works perfectly. I use it at 75Hz with no issue.
